### ISSUE TITLE
sonarWebContext is completly ignored

### ISSUE THREAD

**Issue by PAKalucki** [SonarSource/helm-chart-sonarqube#211] opened 2022-04-23 11:11 UTC
**Describe the bug**
livenessProbe.sonarWebContext, startupProbe.sonarWebContext and readinessProbe.sonarWebContext are completly ignored

**Versions used:**
- Chart Version: 2.0
- SonarQube Version: 9.3
- Helm Version: v3.8.0
- Kubernetes Version: 1.23.5

```yaml
readinessProbe:
  failureThreshold: 10
  sonarWebContext: /sonarqube/

livenessProbe:
  failureThreshold: 10
  sonarWebContext: /sonarqube/

startupProbe:
  failureThreshold: 30
  sonarWebContext: /sonarqube/
```

**Expected behavior**
Startup probe should use path with sonarWebContext value in it.

**Actual behavior**
Startup probe configuration is not updated and it's still trying default path:
```yaml
kind: Event
apiVersion: v1
metadata:
  name: sonarqube-sonarqube-0.16e854da125d9c2e
  namespace: sonarqube
  uid: b416f705-ceeb-45f9-b198-463a73d2517f
  resourceVersion: '15446127'
  creationTimestamp: '2022-04-23T09:36:49Z'
  managedFields:
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-04-23T09:36:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
involvedObject:
  kind: Pod
  namespace: sonarqube
  name: sonarqube-sonarqube-0
  uid: ec35455b-df53-4625-8ee7-12c520630521
  apiVersion: v1
  resourceVersion: '15249745'
  fieldPath: spec.containers{sonarqube}
reason: Unhealthy
message: >-
  Startup probe failed: Get  #"http://10.1.0.20:9000/api/system/status": dial tcp
  10.1.0.20:9000: connect: connection refused
```

**Additional context**
I'm running on Azure AKS
Sonar is up, there are no errors in logs and curl inside node works, everything worked fine with default path /
![image](https://user-images.githubusercontent.com/11369174/164892119-704ec1e5-d4c1-4370-9a34-dd4766c201a4.png)

**Comment by leo-geoffroy-sonarsource** [comment] 2022-04-26 12:58
Hi @PAKalucki 
I could not reproduce your error, I used the following configuration in CE on version 2.0.0 but I have correct probe setup in StatefulSet or Deployment

```yaml
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /test/

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /test/

startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 24
  sonarWebContext: /test/
```
What type of deployment are you using? Can you check the deployment/Statefulset details to check if it is correctly set?

**Comment by leo-geoffroy-sonarsource** [comment] 2022-05-24 15:00
Closing the issue because of no answers

**Closed by leo-geoffroy-sonarsource** 2022-05-24 15:00 UTC
