### ISSUE TITLE
[Q] Plans on hosting a Helm Chart Repo

### ISSUE THREAD

**Issue by k3rnelpan1c-dev** [SonarSource/helm-chart-sonarqube#11] opened 2021-05-14 16:39 UTC
Greetings all,

I am curious if there are any plans to publish this now official SonarSource Chart via a Helm Repository or to stick to the git clone approach for now?
In this vain would, you be interested in CI PRs to publish the chart via [GitHub Pages](https://helm.sh/docs/topics/chart_repository/#github-pages-example)?
I know this repo has just recently migrated ownership and you are still getting set up, so totally understandable if that is not your top priority.

Thank you for providing an official Helm Chart!

**Comment by tobias-trabelsi-sonarsource** [comment] 2021-05-15 10:46
Hi @k3rnelpan1c-dev ,

there are plans on providing a helm repository in the future, but we are currently looking where this would best fit our internal tooling/release processes. i will leave this issue open and close it when we provide a helm repository with the information where to find it

**Comment by k3rnelpan1c-dev** [comment] 2021-05-15 13:29
Hi Tobias,

Thank you for your answer! I kind of expected that and just wanted confirmation.

**Comment by Hokwang** [comment] 2021-05-28 16:02
@tobias-trabelsi-sonarsource as you know, you can simply use gh-pages branch in this repo.

**Comment by czerasz** [comment] 2021-06-03 20:30
@k3rnelpan1c-dev below the method I use.

On a fresh system (new Docker container) I see **NO** "sonar" charts:

```bash
$ helm search repo sonar
Error: no repositories configured
```

Then I add the repo like this:

```bash
helm repo add sonar https://SonarSource.github.io/helm-chart-sonarqube
```

Now I can see the charts (which I believe are associated with the current release):

```bash
$ helm search repo sonar
NAME                	CHART VERSION	APP VERSION    	DESCRIPTION                                       
sonar/sonarqube     	9.6.3        	8.5.1-community	SonarQube is an open sourced code quality scann...
sonar/che           	0.1.5        	7.3.1          	A Helm chart for deploying Eclipse Che to Kuber...
sonar/nexusiq       	1.0.5        	1.63.0         	A Helm chart for Nexus IQ                         
sonar/sonatype-nexus	5.1.0        	3.27.0         	Sonatype Nexus is an open source repository man...
```

In my own chart I use it as a dependency:

```yaml
dependencies:
- name: sonarqube
  version: "9.6.3"
  repository: https://SonarSource.github.io/helm-chart-sonarqube
```

Tested with `helm`:

```bash
$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

**Comment by k3rnelpan1c-dev** [comment] 2021-06-03 21:17
FYI the reason why u find a outdated version / other tools in that 'SonarSource' Helm repo is due to the history of this repository that was ported over from [the source](https://github.com/Oteemo/charts/tree/master/charts/sonarqube). This repo/the Chart has just recently been migrated to be the official SonarSource Helm chart of SonarQube AFAIK.

**Comment by czerasz** [comment] 2021-06-07 14:39
@tobias-trabelsi-sonarsource would You accept a PR which makes this available via GitHub Pages - as @k3rnelpan1c-dev suggested?

**Comment by tobias-trabelsi-sonarsource** [comment] 2021-06-08 06:17
@czerasz no, but i would welcome you to keep an eye open for https://jira.sonarsource.com/browse/MMF-2391 which includes a helm repository in the solution required.
the problem is not about just doing it via github pages, but more about where to put it that fulfills our internal processes as well (the solution in the end might even be gh-pages but with a little more in the background)

**Closed** 2021-09-07 11:19 UTC

**Comment by tobias-trabelsi-sonarsource** [comment] 2021-09-07 11:21
Hello everyone :wave: 
we have now published our helm charts to a user facing helm repository. The visibility on artifact hub will follow soon :tm:
